import { REQUEST_STATUS } from "./enums.js";

export const ALLOWED_TRANSITIONS = {
    [REQUEST_STATUS.PENDING]: [
        REQUEST_STATUS.DISPATCHED,
        REQUEST_STATUS.CANCELLED
    ],

    [REQUEST_STATUS.DISPATCHED]: [
        REQUEST_STATUS.ENROUTE
    ],

    [REQUEST_STATUS.ENROUTE]: [
        REQUEST_STATUS.ARRIVED
    ],

    [REQUEST_STATUS.ARRIVED]: [
        REQUEST_STATUS.PICKED_UP
    ],

    [REQUEST_STATUS.PICKED_UP]: [
        REQUEST_STATUS.COMPLETED
    ],

    [REQUEST_STATUS.COMPLETED]: [],

    [REQUEST_STATUS.CANCELLED]: []
};