export const USER_ROLES = {
    ADMIN: "ADMIN",
    USER: "USER",
    DRIVER: "DRIVER"
};

export const REQUEST_STATUS = {

    PENDING: "PENDING",

    DISPATCHED: "DISPATCHED",

    ARRIVED: "ARRIVED",

    IN_TRANSIT: "IN_TRANSIT",

    COMPLETED: "COMPLETED",

    CANCELLED: "CANCELLED",
};

export const EMERGENCY_TYPES = {
    ACCIDENT: "ACCIDENT",
    HEART_ATTACK: "HEART_ATTACK",
    FIRE: "FIRE",
    OTHER: "OTHER"
};